title: Sabine Laszakovits
url: 'http://sabine.laszakovits.net'
baseurl: '' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-1
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Sabine Laszakovits
tagline: 'Computational linguist'
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name here

#sidebar links
email: sabine.laszakovits@uconn.edu
#phone: 012 345 6789
website: sabine.laszakovits.net #do not add http://

academia-uconn: SabineLaszakovits
facebook: sabine.laszakovits
github: laszabine
keybase: laszabine
linkedin: sabine-laszakovits-a2b5696b
researchgate: Sabine_Laszakovits
stackexchange-linguistics: 1725/laszabine
stackoverflow: 2032421/laszabine
#twitter: '@webjeda'

cv_lastupdate: "October 2020"

dalinakallulli: http://homepage.univie.ac.at/dalina.kallulli/
dianelm: https://lillomartin.linguistics.uconn.edu/
jdb: http://bobaljik.com/
kadirgokgoz: https://linguistics.boun.edu.tr/kadir-gokgoz
kseniabogomolets: http://kseniabogomolets.wixsite.com/mysite
marcindadan: https://marcindadan.com/
pashakoval: http://www.pkoval.org/
thomasgraf: http://thomasgraf.net/
yongsukyoo: https://sites.google.com/site/usefulstone/
